language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
before_install:
  - openssl aes-256-cbc -K $encrypted_c5385d812c08_key -iv $encrypted_c5385d812c08_iv
    -in google-services.json.enc -out google-services.json -d
  - yes | sdkmanager "platforms;android-28"
jdk:
  - oraclejdk8
script:
  - "./gradlew test"
  - "./gradlew assembleDebug"
notifications:
  email: false
